apiVersion: v1
kind: Secret
metadata:
  name: cred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ2YWxheHkwOTMwLmpmcm9nLmlvIjogewoJCQkiYXV0aCI6ICJRV05vYVhRNlFYbDFiV1ZrTWpBeE9WODAiCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson